### ISSUE TITLE
Basic http auth fails with an error 400 since release 3.3.0

### ISSUE THREAD

**Issue by izhar18** [pycontribs/jira#1482]
### Bug summary

I get a 400 when as soon I try to create a JIRA client with basic http_auth. This has been introduced in jira-python version 3.3.0 and does not occur in versions 3.2.0 or earlier.

Error is: JiraError HTTP 400 url: https://JIRA.MY_ORGANISATION/rest/api/2/serverInfo

The details in the 400 suggest that the way the request to the JIRA API is now being routed (or made) has changed? The 400 that I'm getting back from my company's on premise Jira isntance suggests that the API call is being treated as an external call (made from outside our network) even though I haven't set or forced the proxy anywhere in the environment variables or in the jira-python options. This summation is based on the behaviour, however I'm not 100% certain.

Instead of getting a response from the /rest/api/2/serverInfo, I get a response from Trivoli Access Manager which manages any external traffic.

Rolling back to 3.2.0 or earlier resolves this issue.
I have also confirmed that I can get a response back from API just fine using Python requests and also curl.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Server or Data Center (Self-hosted)

### Jira instance version

8.13.22

### jira-python version

3.3.0

### Python Interpreter version

Python 3.10.6

### Which operating systems have you used?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Reproduction steps

```python
# 1. Given a Jira client instance
options = {
		'server': 'https://jira.mycompany.com',
		'verify': '../path/to/certs/company-cert-bundle.crt',
	}

	jira = JIRA(options=options, basic_auth=('username','userpass'))


# 2. When I call the function with argument x
# I can't even get to calling a function, the error occurs at the JIRA client creation step above.
# 3.
...
```

### Stack trace

```python
I'm not comfortable with providing the trace messages messages publicly as they include my company's details.
```

### Expected behaviour

I should be able to create a Jira client and connect to the JIRA API e.g. in version 3.2.0 or earlier, I get:

[INFO] Trying to connect to Jira Server: https://jira.mycompany.com...
[INFO] Verifying connectivity by trying to get fetch details for SVB-7506...
Project Key: SVB
Issue type name: Epic
Reporter: Izhar S
Test succeeded.

### Additional Context

jira==3.3.0

**Comment by tonvanopstal** [comment]
I have similar experiences in Docker/Linux. I am getting the following error:
Exception occurred in JiraUtils.get_all_issues():Unterminated string starting at: line 1 column 7563 (char 7562)
Exception type: JSONDecodeError

Resolution/workaround:
Issue resolved by switching back to older version of python library (changes in Dockerfile)

#RUN pip install --upgrade jira
RUN pip install 'jira==3.2.0'

**Comment by adehad** [comment]
@tonvanopstal I believe your issue is more similar to #1486 which from my testing is fixed in the latest main.

@izhar18 I'd be keen to know how better to help you in this.
Can I first ask if you have any improvements on the latest main `pip install git+https://github.com/pycontribs/jira.git@main` ? As perhaps the same fix applies for this issue.

**Comment by tonvanopstal** [comment]
Hi,

I have tested with RUN pip install git+https://github.com/pycontribs/jira.git@main.
This solves the issue.

When using RUN pip install --upgrade jira
The issue is still there.

Ton

**Comment by adehad** [comment]
@tonvanopstal great, thanks for confirming. We have not released this just yet, I am hoping to see whether we can bundle the HTTP auth fix (if different) to the next patch release. Otherwise I may look into reverting the changes to the ResilientSession

**Comment by tonvanopstal** [comment]
Correction: RUN pip install git+https://github.com/pycontribs/jira.git@main. does not solve my issue. I missed the fact that there is another error message occuring:
Exception occurred in JiraUtils.get_all_issues():Exceeded 30 redirects.

**Comment by izhar18** [comment]
Hi @adehad , yes pip install git+https://github.com/pycontribs/jira.git@main resolves the issue. It seems to have been fixed in the below revision of the module:
pip freeze | grep jira
jira @ git+https://github.com/pycontribs/jira.git@7846ac35a7e219dd3c1cd616a120a920f112b85e

Will the fix be released in the next release? Thanks heaps.

**Comment by adehad** [comment]
Thanks for confirming @izhar18, v3.4.1 now released, will re-open if this is still an issue.

@tonvanopstal I think we should raise a separate issue for what you are describing regarding redirects, following the bug report template as it is difficult to determine the issue with the information you have provided so far.
