### ISSUE TITLE
add_attachment() adds ZIP files as 'text/plain', so they can't be open in JIRA afterwards (problem started in v0.36)

### ISSUE THREAD

**Issue by maxu777** [pycontribs/jira#45]
Hello,

starting with the version 0.36 a new 'MultipartEncoder' method has been introduced in the add_attachment() function and since that all attachments seem to be treated as plan-text files.
Because of that one can't open such a ZIP files directly from JIRA any longer - you'll see the contents of the binary ZIP file.
It worked properly till version 0.35.

Could you please fix that?

Thank you!

PS i found one "quick and dirty" solution - uninstalling "requests-toolbelt" package, but it will be automatically installed next time you want to upgrade the "jira" package.

With kind regards,
Max

**Comment by ssbarnea** [comment]
Solved in trunk, will be included in the next release, later today.

**Comment by maxu777** [comment]
Hello,

i'm sorry to bother you again, but the version 0.44 doesn't seem to fix this issue - or was it too early to test it?
