### ISSUE TITLE
Method add_attachment() error with python 3.8 -- RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by dannylui** [pycontribs/jira#890]
**Describe the bug**
When calling the add_attachment method in python 3.8, we hit RuntimeError: dictionary keys changed during iteration.  We verified that rolling back to python 3.7, the same code works as expected.

**To Reproduce**
```
jira.add_attachment(issue=issue, attachment='/some/path/attachment.txt')
```
1. No additional steps.

**Expected behavior**
File attachement uploaded to JIRA and attached to issue.

**Stack Trace**
```
Traceback (most recent call last):
  File "test_attachments.py", line 302, in <module>
    main()
  File "test_attachments.py", line 298, in main
    test.attachments(args)
  File "test_attachments.py", line 207, in migrate
    self._jira.add_attachment(issue=issue, attachment=attachment_path)
  File "C:\Users\dlui\workspace\test_attachments\venv\lib\site-packages\jira\client.py", line 126, in wrapper
    result = func(*arg_list, **kwargs)
  File "C:\Users\dlui\workspace\test_attachments\venv\lib\site-packages\jira\client.py", line 787, in add_attachment
    url, data=m, headers=CaseInsensitiveDict({'content-type': m.content_type, 'X-Atlassian-Token': 'nocheck'}), retry_data=file_stream)
  File "C:\Users\dlui\workspace\test_attachments\venv\lib\site-packages\jira\utils\__init__.py", line 41, in __init__
    for key, value in super(CaseInsensitiveDict, self).items():
RuntimeError: dictionary keys changed during iteration```
```

**Version Information**
Python Interpreter: 3.8
jira-python: 2.0.0
OS: Windows 10
IPython (Optional): <VERSION>
Other Dependencies:

**Additional context**
None

**Comment by earshinov** [comment]
FYI, this error comes from this change introduced in Python 3.8:
https://bugs.python.org/issue36452

**Comment by ackris** [comment]
Dear JIRA Python API team, 

This issue is still surfacing despite the merge.

My system's python version is `3.8.2` & OS is `Win10`. 

PFB the stack trace.

```
Traceback (most recent call last):
  File "jiratxn.py", line 88, in <module>
    jiratxn()
  File "jiratxn.py", line 81, in jiratxn
    jira.add_attachment(issue=issue, attachment=f)
  File "C:\Users\Kris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jira\client.py", line 126, in wrapper
    result = func(*arg_list, **kwargs)
  File "C:\Users\Kris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jira\client.py", line 787, in add_attachment
    url, data=m, headers=CaseInsensitiveDict({'content-type': m.content_type, 'X-Atlassian-Token': 'nocheck'}), retry_data=file_stream)
  File "C:\Users\Kris\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jira\utils\__init__.py", line 41, in __init__
    for key, value in super(CaseInsensitiveDict, self).items():
RuntimeError: dictionary keys changed during iteration
```

Here is my code snippet

```
for f in listdir(args.reports):
                    try:
                        if f.endswith('.json'):
                            with open(join(args.reports, f), 'rb') as f:
                                jira.add_attachment(issue=issue, attachment=f)
                                print('Successfully added attachment to the '+issue+'')
                    except FileNotFoundError:
                        raise FileNotFoundError('Could not the JSON file you are looking for. Are you sure the path/filename is correct?')
```

I don't want to downgrade python version. 

Regards
Kris

**Comment by wesinator** [comment]
@ssbarnea can you do a new release with this fix ? 

Thanks,

**Comment by amaistrenko-od-ua** [comment]
Dear JIRA Python API team,

I got same issue. 
Python version: 3.8.6. 
And Jenkins (Debian) as a system.

Exception: 
File "/var/jenkins_home/.local/share/virtualenvs/app-J2ca32bp/lib/python3.8/site-packages/jira/client.py", line 126, in wrapper
     result = func(*arg_list, **kwargs)
File "/var/jenkins_home/.local/share/virtualenvs/app-J2ca32bp/lib/python3.8/site-packages/jira/client.py", line 787, in add_attachment
url, data=m, headers=CaseInsensitiveDict({'content-type': m.content_type, 'X-Atlassian-Token': 'nocheck'}), retry_data=file_stream)
File "/var/jenkins_home/.local/share/virtualenvs/app-J2ca32bp/lib/python3.8/site-packages/jira/utils/__init__.py", line 41, in __init__
      for key, value in super(CaseInsensitiveDict, self).items():
RuntimeError: dictionary keys changed during iteration

Thanks.

**Comment by wesinator** [comment]
This is fixed in 3.0 of this package - https://github.com/pycontribs/jira/releases/tag/3.0

**Comment by amaistrenko-od-ua** [comment]
Manually update lib to jira-3.0a1 and jira-3.0a2 from pip, but issue still reproduced.

**Comment by srinubalsu** [comment]
Hi,
If the issue is still reproduced, how will that helps me?

As you said, I still try to use the latest library  jira-3.0a2

Thanks and regards,
Srinu

**Comment by dblanchette** [comment]
It works when using the version 3.0 from GitHub

In poetry's syntax:
`jira = { git = "https://github.com/pycontribs/jira.git", tag = "3.0" }`

I don't know why it is still not released to pypi though.

**Comment by medic8601** [comment]
Hello all,

Still seeing the 2.0 release in pypi as the latest. And the issue still arises with python 3.9. Any ETA on when the 3.0 release will push to pypi?

**Comment by netllama** [comment]
Adding my name to the list of 'me too' since upgrading to python-3.8.x.  

I don't understand why this ticket is closed when there's no fix available yet?

**Comment by abrs907** [comment]
Adding attachments with version 3.0.1 with Python 3.9.5 is working.
`pip install jira==3.0.1`
